name: 1-4
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0-15,22,23 * * *
  watch:
    types: started
  repository_dispatch:
    types: bean_change
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【Android-Чтосмотреть-Dostum】'
        run: |
          node zqkd.js
        env:
          TGUSERID : ${{ secrets.TGUSERID }}
          ZQKDACTIVECODE: ${{ secrets.ZQKDACTIVECODE }}
          ZQKDAPP : ${{ secrets.ZQKDAPP }}
          ZQKDTXAMOUNT: ${{ secrets.ZQKDTXAMOUNT }}
          APIHOST : ${{ secrets.APIHOST }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          #shareOnOff: ${{ secrets.shareOnOff }}
