name: 5-8
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0-18 * * *
  watch:
    types: started
  repository_dispatch:
    types: bean_change
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【Android-Чтосмотреть-Dostum】'
        run: |
          node zqkd.js
        env:
          TGUSERID : ${{ secrets.TGUSERID }}
          ZQKDACTIVECODE: ${{ secrets.ZQKDACTIVECODE }}
          ZQKDAPP : ${{ secrets.ZQKDAPP2 }}
          ZQKDTXAMOUNT: ${{ secrets.ZQKDTXAMOUNT }}
          APIHOST : ${{ secrets.APIHOST }}
