name: Android-Чтосмотреть-收益提现
on:
  workflow_dispatch:
  schedule:
    - cron: '1 23,3,6,10,15 * * *'
  watch:
    types: started
  repository_dispatch:
    types: bean_change
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【Android-Чтосмотреть-gəlir】'
        run: |
          
          node Android-Чтосмотреть-gəlir.js
        env:
          zq_cookie: ${{ secrets.ZQ_COOKIE }}
          zq_withdraw: ${{ secrets.ZQ_WITHDRAW}}
          
