name: Android-Чтосмотреть-oxumaq2
on:
  workflow_dispatch:
  schedule:
    - cron: '1 0-23/6 * * *'
  watch:
    types: started
  repository_dispatch:
    types: bean_change
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【Android-Чтосмотреть-oxumaq2】'
        run: |
          
          node Android-Чтосмотреть-oxumaq2.js
        env:

          zqwzbody2: ${{ secrets.zqwzbody2 }}
          zq_timebody: ${{ secrets.zq_timebody }}
