# File: .github/workflows/repo-sync.yml
name: sync
on:
  schedule:
  - cron:  "7 * */2 * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:na
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/bluesmallpig/scripts"
        source_branch: "main"
        destination_branch: "dv"
        github_token: ${{ secrets.PAT }}
