name: File Sync

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 */3 * *

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: File Sync
        uses: kbrashears5/github-action-file-sync@v2.0.0
        with:
          REPOSITORIES: |
           bluesmallpig/scripts@master
          FILES: |
            zqkd.js
          TOKEN: ${{ secrets.PAT }}
